import ktanesolver.modules as m

MODULE_MAP = {
    'button': m.Button,
    'wires': m.Wires,
    'wiresequence': m.WireSequence,
    'maze': m.Maze,
    'password': m.Password,
    'morsecode': m.MorseCode,
    'simonsays': m.SimonSays,
    'memory': m.Memory,
    'keypad': m.Keypad,
    'complicatedwires': m.ComplicatedWires,
    'whosonfirst': m.WhosOnFirst,
    'colourflash': m.ColourFlash,
    'pianokeys': m.PianoKeys,
    'semaphore': m.Semaphore,
    'emojimath': m.EmojiMath,
    'switches': m.Switches,
    'twobits': m.TwoBits,
    'wordscramble': m.WordScramble,
    'anagrams': m.Anagrams,
    'combinationlock': m.CombinationLock,
    'roundkeypad': m.RoundKeypad,
    'listening': m.Listening,
    'foreignexchangerates': m.ForeignExchangeRates,
    'orientationcube': m.OrientationCube,
    'morsematics': m.Morsematics,
    'connectioncheck': m.ConnectionCheck,
    'letterkeys': m.LetterKeys,
    'forgetmenot': m.ForgetMeNot,
    'astrology': m.Astrology,
    'logic': m.Logic,
    'mysticsquare': m.MysticSquare,
    'crazytalk': m.CrazyTalk,
    'adventuregame': m.AdventureGame,
    'plumbing': m.Plumbing,
    'cruelpianokeys': m.CruelPianoKeys,
    'safetysafe': m.SafetySafe,
    'cryptography': m.Cryptography,
    'chess': m.Chess,
    'mouseinthemaze': m.MouseInTheMaze,
    #'3dmaze': m.3DMaze,
    'sillyslots': m.SillySlots,
    'simonstates': m.SimonStates,

    'zoo': m.Zoo,
    'poetry': m.Poetry,
    'doubleoh': m.DoubleOh,
    'alphabet': m.Alphabet,
    'ledgrid': m.LEDGrid,
    'fastmath': m.FastMath,
    'mortalkombat': m.MortalKombat,
    'wireplacement': m.WirePlacement,

    'binarymemory': m.BinaryMemory,
    'workingtitle': m.WorkingTitle,
    'roger': m.Roger,
    'accesscodes': m.AccessCodes,
    'taxreturns': m.TaxReturns,
    'troll': m.Troll,
    'numbercipher': m.NumberCipher,
    'coloredsquares': m.ColoredSquares,
    'dividedsquares': m.DividedSquares,
    'pathfinder': m.Pathfinder,
    'sevenwires': m.SevenWires,
    'amistake': m.AMistake,
    'epellemoica': m.EpelleMoiCa,
    'coloredbuttons': m.ColoredButtons,
    'colornumbers': m.ColorNumbers,
    'coloredmaze': m.ColoredMaze,
    'doubledigits': m.DoubleDigits,
    'code': m.Code,
    'curlywires': m.CurlyWires,
    'divisiblenumbers': m.DivisibleNumbers,
    'primechecker': m.PrimeChecker,
    'directionalbutton': m.DirectionalButton,
    'nextinline': m.NextInLine,
    'skinnywires': m.SkinnyWires,
    'stars': m.Stars,
    'twords': m.TWords,
    'twopersuasivebuttons': m.TwoPersuasiveButtons,
    'luckydice': m.LuckyDice,
    'constellations': m.Constellations,
}

def modulelist():
    pass