from .Button import Button
from .Wires import Wires
from .WireSequence import WireSequence
from .Maze import Maze
from .Password import Password
from .MorseCode import MorseCode
from .SimonSays import SimonSays
from .Memory import Memory
from .Keypad import Keypad
from .ComplicatedWires import ComplicatedWires
from .WhosOnFirst import WhosOnFirst
from .ColourFlash import ColourFlash
from .PianoKeys import PianoKeys
from .Semaphore import Semaphore
from .EmojiMath import EmojiMath
from .Switches import Switches
from .TwoBits import TwoBits
from .WordScramble import WordScramble
from .Anagrams import Anagrams
from .CombinationLock import CombinationLock
from .RoundKeypad import RoundKeypad
from .Listening import Listening
from .ForeignExchangeRates import ForeignExchangeRates
from .OrientationCube import OrientationCube
from .Morsematics import Morsematics
from .ConnectionCheck import ConnectionCheck
from .LetterKeys import LetterKeys
from .ForgetMeNot import ForgetMeNot
from .Astrology import Astrology