from .Button import Button
from .Wires import Wires
from .WireSequence import WireSequence
from .Maze import Maze
from .Password import Password
from .MorseCode import MorseCode
from .SimonSays import SimonSays
from .Memory import Memory
from .Keypad import Keypad
from .ComplicatedWires import ComplicatedWires
from .WhosOnFirst import WhosOnFirst